/**
 * Infinite Canvas Photos
 * A pan-and-zoom photo gallery that creates an endless exploration experience
 */

class InfiniteCanvas {
    constructor() {
        // DOM elements
        this.container = document.getElementById('canvas-container');
        this.canvas = document.getElementById('canvas');
        this.zoomLevelDisplay = document.getElementById('zoom-level');
        this.loadingOverlay = document.getElementById('loading');

        // Transform state
        this.scale = 1;
        this.translateX = 0;
        this.translateY = 0;

        // Interaction state
        this.isDragging = false;
        this.startX = 0;
        this.startY = 0;
        this.lastX = 0;
        this.lastY = 0;

        // Momentum/inertia
        this.velocityX = 0;
        this.velocityY = 0;
        this.lastMoveTime = 0;
        this.animationFrame = null;

        // Pinch zoom state
        this.initialPinchDistance = 0;
        this.initialScale = 1;

        // Configuration
        this.config = {
            minScale: 0.1,
            maxScale: 5,
            zoomStep: 0.2,
            friction: 0.92,
            minVelocity: 0.1,
            photoSizes: [
                { width: 300, height: 200 },
                { width: 250, height: 350 },
                { width: 400, height: 300 },
                { width: 200, height: 200 },
                { width: 350, height: 250 },
                { width: 280, height: 400 },
            ],
            gridSpacing: 40,
            chunkSize: 2000,
            viewPadding: 500,
        };

        // Photos data
        this.photos = [];
        this.placedPhotos = new Map();
        this.photoElements = new Map();

        // Chunk management for infinite scrolling
        this.loadedChunks = new Set();

        this.init();
    }

    async init() {
        await this.loadPhotos();
        this.setupEventListeners();
        this.centerCanvas();
        this.updateTransform();
        this.updateVisibleChunks();
        this.hideLoading();
    }

    async loadPhotos() {
        // Try to load from photos.json (generated by scan script)
        try {
            const response = await fetch('photos.json');
            if (response.ok) {
                const data = await response.json();
                this.photos = data.photos || [];
            }
        } catch (e) {
            console.log('No photos.json found, using demo mode');
        }

        // If no photos loaded, use placeholder images for demo
        if (this.photos.length === 0) {
            this.photos = this.generateDemoPhotos();
        }
    }

    generateDemoPhotos() {
        // Generate demo photos using placeholder service
        const demoPhotos = [];
        const categories = ['nature', 'city', 'abstract', 'people', 'architecture'];

        for (let i = 0; i < 50; i++) {
            const width = 600 + Math.floor(Math.random() * 400);
            const height = 400 + Math.floor(Math.random() * 400);
            const category = categories[i % categories.length];

            demoPhotos.push({
                id: `demo-${i}`,
                src: `https://picsum.photos/seed/${category}${i}/${width}/${height}`,
                width,
                height,
            });
        }

        return demoPhotos;
    }

    centerCanvas() {
        const rect = this.container.getBoundingClientRect();
        this.translateX = rect.width / 2;
        this.translateY = rect.height / 2;
    }

    setupEventListeners() {
        // Mouse events
        this.container.addEventListener('mousedown', this.onMouseDown.bind(this));
        window.addEventListener('mousemove', this.onMouseMove.bind(this));
        window.addEventListener('mouseup', this.onMouseUp.bind(this));

        // Wheel zoom
        this.container.addEventListener('wheel', this.onWheel.bind(this), { passive: false });

        // Touch events
        this.container.addEventListener('touchstart', this.onTouchStart.bind(this), {
            passive: false,
        });
        this.container.addEventListener('touchmove', this.onTouchMove.bind(this), {
            passive: false,
        });
        this.container.addEventListener('touchend', this.onTouchEnd.bind(this));

        // Control buttons
        document
            .getElementById('zoom-in')
            .addEventListener('click', () => this.zoomBy(this.config.zoomStep));
        document
            .getElementById('zoom-out')
            .addEventListener('click', () => this.zoomBy(-this.config.zoomStep));
        document.getElementById('reset').addEventListener('click', () => this.resetView());

        // Window resize
        window.addEventListener('resize', () => this.updateVisibleChunks());

        // Keyboard controls
        window.addEventListener('keydown', this.onKeyDown.bind(this));
    }

    onMouseDown(e) {
        if (e.button !== 0) return; // Only left click

        this.isDragging = true;
        this.startX = e.clientX - this.translateX;
        this.startY = e.clientY - this.translateY;
        this.lastX = e.clientX;
        this.lastY = e.clientY;
        this.lastMoveTime = Date.now();
        this.velocityX = 0;
        this.velocityY = 0;

        this.container.classList.add('dragging');
        this.cancelMomentum();
    }

    onMouseMove(e) {
        if (!this.isDragging) return;

        const now = Date.now();
        const dt = now - this.lastMoveTime;

        if (dt > 0) {
            this.velocityX = ((e.clientX - this.lastX) / dt) * 16;
            this.velocityY = ((e.clientY - this.lastY) / dt) * 16;
        }

        this.translateX = e.clientX - this.startX;
        this.translateY = e.clientY - this.startY;

        this.lastX = e.clientX;
        this.lastY = e.clientY;
        this.lastMoveTime = now;

        this.updateTransform();
        this.updateVisibleChunks();
    }

    onMouseUp() {
        if (!this.isDragging) return;

        this.isDragging = false;
        this.container.classList.remove('dragging');

        // Start momentum animation if velocity is significant
        if (
            Math.abs(this.velocityX) > this.config.minVelocity ||
            Math.abs(this.velocityY) > this.config.minVelocity
        ) {
            this.startMomentum();
        }
    }

    onWheel(e) {
        e.preventDefault();

        const rect = this.container.getBoundingClientRect();
        const mouseX = e.clientX - rect.left;
        const mouseY = e.clientY - rect.top;

        // Calculate zoom direction
        const delta = -Math.sign(e.deltaY) * this.config.zoomStep;

        this.zoomAt(mouseX, mouseY, delta);
    }

    onTouchStart(e) {
        if (e.touches.length === 1) {
            // Single touch - pan
            const touch = e.touches[0];
            this.isDragging = true;
            this.startX = touch.clientX - this.translateX;
            this.startY = touch.clientY - this.translateY;
            this.lastX = touch.clientX;
            this.lastY = touch.clientY;
            this.lastMoveTime = Date.now();
            this.velocityX = 0;
            this.velocityY = 0;
            this.cancelMomentum();
        } else if (e.touches.length === 2) {
            // Pinch zoom
            e.preventDefault();
            this.isDragging = false;
            this.initialPinchDistance = this.getPinchDistance(e.touches);
            this.initialScale = this.scale;
        }
    }

    onTouchMove(e) {
        if (e.touches.length === 1 && this.isDragging) {
            const touch = e.touches[0];
            const now = Date.now();
            const dt = now - this.lastMoveTime;

            if (dt > 0) {
                this.velocityX = ((touch.clientX - this.lastX) / dt) * 16;
                this.velocityY = ((touch.clientY - this.lastY) / dt) * 16;
            }

            this.translateX = touch.clientX - this.startX;
            this.translateY = touch.clientY - this.startY;

            this.lastX = touch.clientX;
            this.lastY = touch.clientY;
            this.lastMoveTime = now;

            this.updateTransform();
            this.updateVisibleChunks();
        } else if (e.touches.length === 2) {
            e.preventDefault();
            const currentDistance = this.getPinchDistance(e.touches);
            const scaleChange = currentDistance / this.initialPinchDistance;

            // Get center point of pinch
            const centerX = (e.touches[0].clientX + e.touches[1].clientX) / 2;
            const centerY = (e.touches[0].clientY + e.touches[1].clientY) / 2;
            const rect = this.container.getBoundingClientRect();

            const newScale = Math.max(
                this.config.minScale,
                Math.min(this.config.maxScale, this.initialScale * scaleChange)
            );

            // Zoom towards pinch center
            const canvasX = (centerX - rect.left - this.translateX) / this.scale;
            const canvasY = (centerY - rect.top - this.translateY) / this.scale;

            this.scale = newScale;
            this.translateX = centerX - rect.left - canvasX * this.scale;
            this.translateY = centerY - rect.top - canvasY * this.scale;

            this.updateTransform();
            this.updateZoomDisplay();
            this.updateVisibleChunks();
        }
    }

    onTouchEnd(e) {
        if (e.touches.length === 0) {
            this.isDragging = false;

            if (
                Math.abs(this.velocityX) > this.config.minVelocity ||
                Math.abs(this.velocityY) > this.config.minVelocity
            ) {
                this.startMomentum();
            }
        } else if (e.touches.length === 1) {
            // Reset to single touch pan
            const touch = e.touches[0];
            this.isDragging = true;
            this.startX = touch.clientX - this.translateX;
            this.startY = touch.clientY - this.translateY;
            this.lastX = touch.clientX;
            this.lastY = touch.clientY;
        }
    }

    getPinchDistance(touches) {
        const dx = touches[0].clientX - touches[1].clientX;
        const dy = touches[0].clientY - touches[1].clientY;
        return Math.sqrt(dx * dx + dy * dy);
    }

    onKeyDown(e) {
        const panAmount = 100;

        switch (e.key) {
            case 'ArrowUp':
                this.translateY += panAmount;
                break;
            case 'ArrowDown':
                this.translateY -= panAmount;
                break;
            case 'ArrowLeft':
                this.translateX += panAmount;
                break;
            case 'ArrowRight':
                this.translateX -= panAmount;
                break;
            case '+':
            case '=':
                this.zoomBy(this.config.zoomStep);
                return;
            case '-':
                this.zoomBy(-this.config.zoomStep);
                return;
            case '0':
                this.resetView();
                return;
            default:
                return;
        }

        this.updateTransform();
        this.updateVisibleChunks();
    }

    zoomAt(x, y, delta) {
        const oldScale = this.scale;
        const newScale = Math.max(
            this.config.minScale,
            Math.min(this.config.maxScale, this.scale + delta)
        );

        if (newScale === oldScale) return;

        // Calculate the point in canvas coordinates
        const canvasX = (x - this.translateX) / oldScale;
        const canvasY = (y - this.translateY) / oldScale;

        this.scale = newScale;

        // Adjust translation to zoom towards the point
        this.translateX = x - canvasX * this.scale;
        this.translateY = y - canvasY * this.scale;

        this.updateTransform();
        this.updateZoomDisplay();
        this.updateVisibleChunks();
    }

    zoomBy(delta) {
        const rect = this.container.getBoundingClientRect();
        this.zoomAt(rect.width / 2, rect.height / 2, delta);
    }

    resetView() {
        this.scale = 1;
        this.centerCanvas();
        this.updateTransform();
        this.updateZoomDisplay();
        this.updateVisibleChunks();
    }

    startMomentum() {
        this.cancelMomentum();

        const animate = () => {
            this.velocityX *= this.config.friction;
            this.velocityY *= this.config.friction;

            if (
                Math.abs(this.velocityX) < this.config.minVelocity &&
                Math.abs(this.velocityY) < this.config.minVelocity
            ) {
                return;
            }

            this.translateX += this.velocityX;
            this.translateY += this.velocityY;

            this.updateTransform();
            this.updateVisibleChunks();

            this.animationFrame = requestAnimationFrame(animate);
        };

        this.animationFrame = requestAnimationFrame(animate);
    }

    cancelMomentum() {
        if (this.animationFrame) {
            cancelAnimationFrame(this.animationFrame);
            this.animationFrame = null;
        }
    }

    updateTransform() {
        this.canvas.style.transform = `translate(${this.translateX}px, ${this.translateY}px) scale(${this.scale})`;
    }

    updateZoomDisplay() {
        this.zoomLevelDisplay.textContent = `${Math.round(this.scale * 100)}%`;
    }

    updateVisibleChunks() {
        const rect = this.container.getBoundingClientRect();
        const padding = this.config.viewPadding;
        const chunkSize = this.config.chunkSize;

        // Calculate visible area in canvas coordinates
        const viewLeft = (-this.translateX - padding) / this.scale;
        const viewTop = (-this.translateY - padding) / this.scale;
        const viewRight = (rect.width - this.translateX + padding) / this.scale;
        const viewBottom = (rect.height - this.translateY + padding) / this.scale;

        // Calculate which chunks are needed
        const startChunkX = Math.floor(viewLeft / chunkSize);
        const endChunkX = Math.floor(viewRight / chunkSize);
        const startChunkY = Math.floor(viewTop / chunkSize);
        const endChunkY = Math.floor(viewBottom / chunkSize);

        const neededChunks = new Set();

        for (let cx = startChunkX; cx <= endChunkX; cx++) {
            for (let cy = startChunkY; cy <= endChunkY; cy++) {
                const chunkKey = `${cx},${cy}`;
                neededChunks.add(chunkKey);

                if (!this.loadedChunks.has(chunkKey)) {
                    this.loadChunk(cx, cy);
                }
            }
        }

        // Remove chunks that are no longer visible
        for (const chunkKey of this.loadedChunks) {
            if (!neededChunks.has(chunkKey)) {
                this.unloadChunk(chunkKey);
            }
        }
    }

    loadChunk(chunkX, chunkY) {
        const chunkKey = `${chunkX},${chunkY}`;
        if (this.loadedChunks.has(chunkKey)) return;

        this.loadedChunks.add(chunkKey);

        const chunkSize = this.config.chunkSize;
        const baseX = chunkX * chunkSize;
        const baseY = chunkY * chunkSize;

        // Use seeded random for consistent placement
        const seed = this.hashCode(`${chunkX},${chunkY}`);
        const random = this.seededRandom(seed);

        // Determine number of photos in this chunk
        const numPhotos = 8 + Math.floor(random() * 5);

        for (let i = 0; i < numPhotos; i++) {
            const photoIndex = Math.floor(random() * this.photos.length);
            const photo = this.photos[photoIndex];
            const sizeConfig =
                this.config.photoSizes[Math.floor(random() * this.config.photoSizes.length)];

            const x = baseX + random() * (chunkSize - sizeConfig.width - this.config.gridSpacing);
            const y = baseY + random() * (chunkSize - sizeConfig.height - this.config.gridSpacing);

            const photoKey = `${chunkKey}-${i}`;
            this.createPhotoElement(photoKey, photo, x, y, sizeConfig.width, sizeConfig.height);
        }
    }

    unloadChunk(chunkKey) {
        // Remove all photos in this chunk
        for (const [photoKey, element] of this.photoElements) {
            if (photoKey.startsWith(chunkKey + '-')) {
                element.remove();
                this.photoElements.delete(photoKey);
            }
        }

        this.loadedChunks.delete(chunkKey);
    }

    createPhotoElement(key, photo, x, y, width, height) {
        const container = document.createElement('div');
        container.className = 'photo-item';
        container.style.left = `${x}px`;
        container.style.top = `${y}px`;
        container.style.width = `${width}px`;
        container.style.height = `${height}px`;

        const placeholder = document.createElement('div');
        placeholder.className = 'placeholder';
        container.appendChild(placeholder);

        const img = document.createElement('img');
        img.alt = photo.id || 'Photo';
        img.loading = 'lazy';

        img.onload = () => {
            img.classList.add('loaded');
            placeholder.remove();
        };

        img.onerror = () => {
            placeholder.innerHTML =
                '<span style="color: #666; font-size: 12px;">Failed to load</span>';
        };

        img.src = photo.src;
        container.appendChild(img);

        this.canvas.appendChild(container);
        this.photoElements.set(key, container);
    }

    // Utility: simple hash function for seeding
    hashCode(str) {
        let hash = 0;
        for (let i = 0; i < str.length; i++) {
            const char = str.charCodeAt(i);
            hash = (hash << 5) - hash + char;
            hash = hash & hash;
        }
        return Math.abs(hash);
    }

    // Utility: seeded random number generator
    seededRandom(seed) {
        return function () {
            seed = (seed * 1103515245 + 12345) & 0x7fffffff;
            return seed / 0x7fffffff;
        };
    }

    hideLoading() {
        this.loadingOverlay.classList.add('hidden');
    }
}

// Initialize the canvas when DOM is ready
document.addEventListener('DOMContentLoaded', () => {
    window.infiniteCanvas = new InfiniteCanvas();
});
