/* Frequencies — fashion collections reaction data for /matriximg/.
   123 looks from the Fashion & accessories category of the
   European-shows 2026 catalog (designboom / dezeen).
   Fields: id, title (from the image slug), source (outlet),
   photo (image URL), v/e (0-1 seeded board position),
   polar (crowd spread), count (seeded reactions). */
window.FREQZ_IMG = {
  issue: 1,
  date: 'August 7, 2026',
  looks: [
    { id: 'audemars-piguet-swatch-pocket-watch-playful-pop-twist-design',
      title: 'Audemars Piguet Swatch Pocket Watch Playful Pop Twist', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/05/audemars-piguet-swatch-pocket-watch-playful-pop-twist-designboom-5.jpg',
      v: 0.55, e: 0.66, polar: 0.45, count: 1037 },
    { id: 'google-samsung-intelligent-eyewear-design-dezeen-936-hero2',
      title: 'Google Samsung Intelligent Eyewear Design', source: 'Dezeen',
      photo: 'https://static.dezeen.com/uploads/2026/05/google-samsung-intelligent-eyewear-design_dezeen_936_hero2.jpg',
      v: 0.16, e: 0.15, polar: 0.34, count: 3601 },
    { id: 'multicolor-windows-luca-nichetto-watch-unimatic-designboom-b',
      title: 'Multicolor Windows Luca Nichetto Watch UNIMATIC', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/01/multicolor-windows-luca-nichetto-watch-UNIMATIC-designboom-ban.jpg',
      v: 0.72, e: 0.75, polar: 0.57, count: 434 },
    { id: 'kosuke-tsumura-44-pocket-parka-survival-wearable-space-final',
      title: 'Kosuke Tsumura 44 Pocket Parka Survival Wearable Space Final Home', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/03/kosuke-tsumura-44-pocket-parka-survival-wearable-space-final-home-designboom-11.jpg',
      v: 0.27, e: 0.16, polar: 0.46, count: 3958 },
    { id: 'laerke-ryom-garments-dezeen-2364-col-3',
      title: 'Laerke Ryom Garments', source: 'Dezeen',
      photo: 'https://static.dezeen.com/uploads/2026/03/laerke-ryom-garments_dezeen_2364_col_3.jpg',
      v: 0.28, e: 0.76, polar: 0.38, count: 868 },
    { id: 'night-vision-watch-glows-dark-luminescent-resin-green-rubber',
      title: 'Night Vision Watch Glows Dark Luminescent Resin Green Rubber Bell Ross Br X3', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/02/night-vision-watch-glows-dark-luminescent-resin-green-rubber-bell-ross-br-x3-designboom-08.jpg',
      v: 0.48, e: 0.58, polar: 0.37, count: 538 },
    { id: 'origami-inspired-watch-casio-texture-washi-paper-designboom-',
      title: 'Origami Inspired Watch Casio Texture Washi Paper', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/02/origami-inspired-watch-casio-texture-washi-paper-designboom-02.jpg',
      v: 0.38, e: 0.53, polar: 0.58, count: 3225 },
    { id: 'air-pressure-gauges-mixing-consoles-design-otsuka-lotec-watc',
      title: 'Air Pressure Gauges Mixing Consoles Design Otsuka Lotec Watch No', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/03/air-pressure-gauges-mixing-consoles-design-otsuka-lotec-watch-no-8-designboom-ban.jpg',
      v: 0.68, e: 0.74, polar: 0.42, count: 3847 },
    { id: 'night-vision-watch-glows-dark-luminescent-resin-green-rubber-2',
      title: 'Night Vision Watch Glows Dark Luminescent Resin Green Rubber Bell Ross Br X3', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/02/night-vision-watch-glows-dark-luminescent-resin-green-rubber-bell-ross-br-x3-designboom-07.jpg',
      v: 0.24, e: 0.80, polar: 0.36, count: 3922 },
    { id: 'audemars-piguet-swatch-pocket-watch-playful-pop-twist-design-2',
      title: 'Audemars Piguet Swatch Pocket Watch Playful Pop Twist', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/05/audemars-piguet-swatch-pocket-watch-playful-pop-twist-designboom-05.jpg',
      v: 0.79, e: 0.80, polar: 0.41, count: 4453 },
    { id: 'origami-inspired-watch-casio-texture-washi-paper-designboom--2',
      title: 'Origami Inspired Watch Casio Texture Washi Paper', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/02/origami-inspired-watch-casio-texture-washi-paper-designboom-01.jpg',
      v: 0.73, e: 0.68, polar: 0.44, count: 941 },
    { id: 'pocket-watch-inspired-clock-time-balmuda-designboom-700-500x',
      title: 'Pocket Watch Inspired Clock Time Balmuda', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/03/pocket-watch-inspired-clock-time-balmuda-designboom-700-500x400-22b08q85r170.jpg',
      v: 0.18, e: 0.68, polar: 0.45, count: 4162 },
    { id: 'christo-logan-good-plus-evil-ways-watch-rotating-designboom-',
      title: 'Christo Logan Good Plus Evil Ways Watch Rotating', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/04/christo-logan-good-plus-evil-ways-watch-rotating-designboom-1800-1.jpg',
      v: 0.66, e: 0.40, polar: 0.45, count: 4947 },
    { id: 'audemars-piguet-swatch-pocket-watch-playful-pop-twist-design-2-2',
      title: 'Audemars Piguet Swatch Pocket Watch Playful Pop Twist', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/05/audemars-piguet-swatch-pocket-watch-playful-pop-twist-designboom-07.jpg',
      v: 0.69, e: 0.71, polar: 0.36, count: 4453 },
    { id: 'jins-eyewear-thomas-heatherwick-glasses-metal-resin-dezeen-2',
      title: 'Jins Eyewear Thomas Heatherwick Glasses Metal Resin', source: 'Dezeen',
      photo: 'https://static.dezeen.com/uploads/2026/05/jins-eyewear-thomas-heatherwick-glasses-metal-resin_dezeen_2364_col_1.jpg',
      v: 0.48, e: 0.58, polar: 0.38, count: 3871 },
    { id: 'obro-wearable-collection-leftover-leather-powder-translucent',
      title: 'Obro Wearable Collection Leftover Leather Powder Translucent Composite Material Okunote', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/01/obro-wearable-collection-leftover-leather-powder-translucent-composite-material-okunote-designboom-1800-3.jpg',
      v: 0.70, e: 0.36, polar: 0.37, count: 3121 },
    { id: 'audemars-piguet-swatch-pocket-watch-playful-pop-twist-design-2-2-2',
      title: 'Audemars Piguet Swatch Pocket Watch Playful Pop Twist', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/05/audemars-piguet-swatch-pocket-watch-playful-pop-twist-designboom-1800-1.jpg',
      v: 0.39, e: 0.37, polar: 0.40, count: 4081 },
    { id: 'origami-inspired-watch-casio-texture-washi-paper-designboom--2-2',
      title: 'Origami Inspired Watch Casio Texture Washi Paper', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/02/origami-inspired-watch-casio-texture-washi-paper-designboom-04.jpg',
      v: 0.26, e: 0.80, polar: 0.43, count: 1315 },
    { id: 'brushed-metal-fold-watch-time-shadow-layered-architectural-d',
      title: 'Brushed Metal Fold Watch Time Shadow Layered Architectural', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/02/brushed-metal-fold-watch-time-shadow-layered-architectural-dials500.jpg',
      v: 0.37, e: 0.20, polar: 0.56, count: 4097 },
    { id: 'astronomy-watch-ressence-terumasa-ikeda-dials-planets-design',
      title: 'Astronomy Watch Ressence Terumasa Ikeda Dials Planets', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/02/astronomy-watch-ressence-terumasa-ikeda-dials-planets-designboom-06.jpg',
      v: 0.27, e: 0.66, polar: 0.50, count: 1434 },
    { id: 'collagen-dinosaur-designer-handbag-lab-grown-leather-designb',
      title: 'Collagen Dinosaur Designer Handbag Lab Grown Leather', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/04/collagen-dinosaur-designer-handbag-lab-grown-leather-designboom-03.jpg',
      v: 0.65, e: 0.39, polar: 0.42, count: 3634 },
    { id: 'astronomy-watch-ressence-terumasa-ikeda-dials-planets-design-2',
      title: 'Astronomy Watch Ressence Terumasa Ikeda Dials Planets', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/02/astronomy-watch-ressence-terumasa-ikeda-dials-planets-designboom-04.jpg',
      v: 0.17, e: 0.70, polar: 0.36, count: 2808 },
    { id: 'laerke-ryom-garments-dezeen-2364-col-10',
      title: 'Laerke Ryom Garments', source: 'Dezeen',
      photo: 'https://static.dezeen.com/uploads/2026/03/laerke-ryom-garments_dezeen_2364_col_10.jpg',
      v: 0.65, e: 0.87, polar: 0.43, count: 3514 },
    { id: 'origami-inspired-watch-casio-texture-washi-paper-designboom--2-2-2',
      title: 'Origami Inspired Watch Casio Texture Washi Paper', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/02/origami-inspired-watch-casio-texture-washi-paper-designboom-1800-1.jpg',
      v: 0.44, e: 0.40, polar: 0.41, count: 3129 },
    { id: 'laerke-ryom-garments-dezeen-2364-col-6',
      title: 'Laerke Ryom Garments', source: 'Dezeen',
      photo: 'https://static.dezeen.com/uploads/2026/03/laerke-ryom-garments_dezeen_2364_col_6.jpg',
      v: 0.83, e: 0.23, polar: 0.33, count: 3533 },
    { id: 'jins-eyewear-thomas-heatherwick-glasses-metal-resin-dezeen-2-2',
      title: 'Jins Eyewear Thomas Heatherwick Glasses Metal Resin', source: 'Dezeen',
      photo: 'https://static.dezeen.com/uploads/2026/05/jins-eyewear-thomas-heatherwick-glasses-metal-resin_dezeen_2364_col_0.jpg',
      v: 0.45, e: 0.69, polar: 0.55, count: 2775 },
    { id: 'laerke-ryom-garments-dezeen-2364-col-5',
      title: 'Laerke Ryom Garments', source: 'Dezeen',
      photo: 'https://static.dezeen.com/uploads/2026/03/laerke-ryom-garments_dezeen_2364_col_5.jpg',
      v: 0.54, e: 0.41, polar: 0.50, count: 4399 },
    { id: 'laerke-ryom-garments-dezeen-2364-col-4-1',
      title: 'Laerke Ryom Garments', source: 'Dezeen',
      photo: 'https://static.dezeen.com/uploads/2026/03/laerke-ryom-garments_dezeen_2364_col_4-1.jpg',
      v: 0.53, e: 0.36, polar: 0.47, count: 1652 },
    { id: 'kosuke-tsumura-44-pocket-parka-survival-wearable-space-final-2',
      title: 'Kosuke Tsumura 44 Pocket Parka Survival Wearable Space Final Home', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/03/kosuke-tsumura-44-pocket-parka-survival-wearable-space-final-home-designboom-06.jpg',
      v: 0.60, e: 0.23, polar: 0.40, count: 4164 },
    { id: 'audemars-piguet-swatch-pocket-watch-playful-pop-twist-design-2-2-2-2',
      title: 'Audemars Piguet Swatch Pocket Watch Playful Pop Twist', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/05/audemars-piguet-swatch-pocket-watch-playful-pop-twist-designboom-01.jpg',
      v: 0.78, e: 0.24, polar: 0.52, count: 1813 },
    { id: 'jins-thomas-heatherwick-eyewear-glasses-dezeen-2364-col-0',
      title: 'Jins Thomas Heatherwick Eyewear Glasses', source: 'Dezeen',
      photo: 'https://static.dezeen.com/uploads/2026/05/jins-thomas-heatherwick-eyewear-glasses_dezeen_2364_col_0.jpg',
      v: 0.63, e: 0.66, polar: 0.45, count: 686 },
    { id: 'laerke-ryom-garments-dezeen-2364-col-1',
      title: 'Laerke Ryom Garments', source: 'Dezeen',
      photo: 'https://static.dezeen.com/uploads/2026/03/laerke-ryom-garments_dezeen_2364_col_1.jpg',
      v: 0.23, e: 0.48, polar: 0.57, count: 5016 },
    { id: 'night-vision-watch-glows-dark-luminescent-resin-green-rubber-2-2',
      title: 'Night Vision Watch Glows Dark Luminescent Resin Green Rubber Bell Ross Br X3', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/02/night-vision-watch-glows-dark-luminescent-resin-green-rubber-bell-ross-br-x3-designboom-06.jpg',
      v: 0.83, e: 0.47, polar: 0.50, count: 3298 },
    { id: 'kosuke-tsumura-44-pocket-parka-survival-wearable-space-final-2-2',
      title: 'Kosuke Tsumura 44 Pocket Parka Survival Wearable Space Final Home', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/03/kosuke-tsumura-44-pocket-parka-survival-wearable-space-final-home-designboom-08.jpg',
      v: 0.83, e: 0.29, polar: 0.42, count: 982 },
    { id: 'night-vision-watch-glows-dark-luminescent-resin-green-rubber-2-2-2',
      title: 'Night Vision Watch Glows Dark Luminescent Resin Green Rubber Bell Ross Br X3', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/02/night-vision-watch-glows-dark-luminescent-resin-green-rubber-bell-ross-br-x3-designboom-1800.jpg',
      v: 0.82, e: 0.15, polar: 0.49, count: 4819 },
    { id: 'audemars-piguet-swatch-pocket-watch-playful-pop-twist-design-2-2-2-2-2',
      title: 'Audemars Piguet Swatch Pocket Watch Playful Pop Twist', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/05/audemars-piguet-swatch-pocket-watch-playful-pop-twist-designboom-13.jpg',
      v: 0.82, e: 0.15, polar: 0.32, count: 4762 },
    { id: 'audemars-piguet-swatch-pocket-watch-playful-pop-twist-design-2-2-2-2-2-2',
      title: 'Audemars Piguet Swatch Pocket Watch Playful Pop Twist', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/05/audemars-piguet-swatch-pocket-watch-playful-pop-twist-designboom-2.jpg',
      v: 0.63, e: 0.23, polar: 0.49, count: 3775 },
    { id: 'jins-eyewear-thomas-heatherwick-glasses-metal-resin-dezeen-2-2-2',
      title: 'Jins Eyewear Thomas Heatherwick Glasses Metal Resin', source: 'Dezeen',
      photo: 'https://static.dezeen.com/uploads/2026/05/jins-eyewear-thomas-heatherwick-glasses-metal-resin_dezeen_2364_col_4.jpg',
      v: 0.83, e: 0.69, polar: 0.39, count: 2419 },
    { id: 'laerke-ryom-garments-dezeen-2364-col-2',
      title: 'Laerke Ryom Garments', source: 'Dezeen',
      photo: 'https://static.dezeen.com/uploads/2026/03/laerke-ryom-garments_dezeen_2364_col_2.jpg',
      v: 0.59, e: 0.54, polar: 0.39, count: 2973 },
    { id: 'christo-logan-good-plus-evil-ways-watch-rotating-designboom--2',
      title: 'Christo Logan Good Plus Evil Ways Watch Rotating', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/04/christo-logan-good-plus-evil-ways-watch-rotating-designboom-700-500x400-22b08q85r120.jpg',
      v: 0.85, e: 0.66, polar: 0.33, count: 2346 },
    { id: 'collagen-dinosaur-designer-handbag-lab-grown-leather-designb-2',
      title: 'Collagen Dinosaur Designer Handbag Lab Grown Leather', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/04/collagen-dinosaur-designer-handbag-lab-grown-leather-designboom-01.jpg',
      v: 0.57, e: 0.37, polar: 0.47, count: 3483 },
    { id: 'kosuke-tsumura-44-pocket-parka-survival-wearable-space-final-2-2-2',
      title: 'Kosuke Tsumura 44 Pocket Parka Survival Wearable Space Final Home', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/03/kosuke-tsumura-44-pocket-parka-survival-wearable-space-final-home-designboom-05.jpg',
      v: 0.26, e: 0.72, polar: 0.55, count: 2082 },
    { id: 'audemars-piguet-swatch-pocket-watch-playful-pop-twist-design-2-2-2-2-2-2-2',
      title: 'Audemars Piguet Swatch Pocket Watch Playful Pop Twist', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/05/audemars-piguet-swatch-pocket-watch-playful-pop-twist-designboom-3.jpg',
      v: 0.29, e: 0.25, polar: 0.42, count: 2951 },
    { id: 'audemars-piguet-swatch-pocket-watch-playful-pop-twist-design-2-2-2-2-2-2-2-2',
      title: 'Audemars Piguet Swatch Pocket Watch Playful Pop Twist', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/05/audemars-piguet-swatch-pocket-watch-playful-pop-twist-designboom-8.jpg',
      v: 0.66, e: 0.76, polar: 0.56, count: 952 },
    { id: 'audemars-piguet-swatch-pocket-watch-playful-pop-twist-design-2-2-2-2-2-2-2-2-2',
      title: 'Audemars Piguet Swatch Pocket Watch Playful Pop Twist Large2', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/05/audemars-piguet-swatch-pocket-watch-playful-pop-twist-designboom-large2.jpg',
      v: 0.53, e: 0.45, polar: 0.49, count: 4833 },
    { id: 'audemars-piguet-swatch-pocket-watch-playful-pop-twist-design-2-2-2-2-2-2-2-2-2-2',
      title: 'Audemars Piguet Swatch Pocket Watch Playful Pop Twist', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/05/audemars-piguet-swatch-pocket-watch-playful-pop-twist-designboom-700-1-500x400-22b08q85r891.jpg',
      v: 0.60, e: 0.87, polar: 0.45, count: 4077 },
    { id: 'multicolor-windows-luca-nichetto-watch-unimatic-designboom-0',
      title: 'Multicolor Windows Luca Nichetto Watch UNIMATIC', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/01/multicolor-windows-luca-nichetto-watch-UNIMATIC-designboom-05.jpg',
      v: 0.39, e: 0.67, polar: 0.39, count: 3853 },
    { id: 'laerke-ryom-garments-dezeen-2364-col-9',
      title: 'Laerke Ryom Garments', source: 'Dezeen',
      photo: 'https://static.dezeen.com/uploads/2026/03/laerke-ryom-garments_dezeen_2364_col_9.jpg',
      v: 0.71, e: 0.25, polar: 0.52, count: 3315 },
    { id: 'google-samsung-intelligent-eyewear-design-dezeen-1704-col-1',
      title: 'Google Samsung Intelligent Eyewear Design', source: 'Dezeen',
      photo: 'https://static.dezeen.com/uploads/2026/05/google-samsung-intelligent-eyewear-design_dezeen_1704_col_1.jpg',
      v: 0.82, e: 0.81, polar: 0.57, count: 1039 },
    { id: 'night-vision-watch-glows-dark-luminescent-resin-green-rubber-2-2-2-2',
      title: 'Night Vision Watch Glows Dark Luminescent Resin Green Rubber Bell Ross Br X3', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/02/night-vision-watch-glows-dark-luminescent-resin-green-rubber-bell-ross-br-x3-designboom-02.jpg',
      v: 0.84, e: 0.51, polar: 0.37, count: 943 },
    { id: 'astronomy-watch-ressence-terumasa-ikeda-dials-planets-design-2-2',
      title: 'Astronomy Watch Ressence Terumasa Ikeda Dials Planets', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/02/astronomy-watch-ressence-terumasa-ikeda-dials-planets-designboom-08.jpg',
      v: 0.59, e: 0.54, polar: 0.38, count: 4103 },
    { id: 'eyewear-thomas-heatherwick-jins-glasses-dezeen-2364-col-0',
      title: 'Eyewear Thomas Heatherwick Jins Glasses', source: 'Dezeen',
      photo: 'https://static.dezeen.com/uploads/2026/05/eyewear-thomas-heatherwick-jins-glasses_dezeen_2364_col_0.jpg',
      v: 0.69, e: 0.50, polar: 0.54, count: 3018 },
    { id: 'collagen-dinosaur-designer-handbag-lab-grown-leather-designb-2-2',
      title: 'Collagen Dinosaur Designer Handbag Lab Grown Leather', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/04/collagen-dinosaur-designer-handbag-lab-grown-leather-designboom-05.jpg',
      v: 0.66, e: 0.18, polar: 0.30, count: 4513 },
    { id: 'kosuke-tsumura-44-pocket-parka-survival-wearable-space-final-2-2-2-2',
      title: 'Kosuke Tsumura 44 Pocket Parka Survival Wearable Space Final Home', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/03/kosuke-tsumura-44-pocket-parka-survival-wearable-space-final-home-designboom-03.jpg',
      v: 0.24, e: 0.79, polar: 0.53, count: 3250 },
    { id: 'collagen-dinosaur-designer-handbag-lab-grown-leather-designb-2-2-2',
      title: 'Collagen Dinosaur Designer Handbag Lab Grown Leather', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/04/collagen-dinosaur-designer-handbag-lab-grown-leather-designboom-700-500x400-22b08q85r012.jpg',
      v: 0.55, e: 0.75, polar: 0.44, count: 3265 },
    { id: 'air-pressure-gauges-mixing-consoles-design-otsuka-lotec-watc-2',
      title: 'Air Pressure Gauges Mixing Consoles Design Otsuka Lotec Watch No', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/03/air-pressure-gauges-mixing-consoles-design-otsuka-lotec-watch-no-8-designboom-05.jpg',
      v: 0.39, e: 0.40, polar: 0.41, count: 4466 },
    { id: 'audemars-piguet-swatch-pocket-watch-playful-pop-twist-design-2-2-2-2-2-2-2-2-2-2-2',
      title: 'Audemars Piguet Swatch Pocket Watch Playful Pop Twist', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/05/audemars-piguet-swatch-pocket-watch-playful-pop-twist-designboom-700-1-250x200-22b08q85r891.jpg',
      v: 0.38, e: 0.68, polar: 0.43, count: 1150 },
    { id: 'christo-logan-good-plus-evil-ways-watch-rotating-designboom--2-2',
      title: 'Christo Logan Good Plus Evil Ways Watch Rotating', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/04/christo-logan-good-plus-evil-ways-watch-rotating-designboom-1800-2.jpg',
      v: 0.62, e: 0.75, polar: 0.31, count: 4870 },
    { id: 'astronomy-watch-ressence-terumasa-ikeda-dials-planets-design-2-2-2',
      title: 'Astronomy Watch Ressence Terumasa Ikeda Dials Planets', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/02/astronomy-watch-ressence-terumasa-ikeda-dials-planets-designboom-1800.jpg',
      v: 0.83, e: 0.28, polar: 0.51, count: 3278 },
    { id: 'audemars-piguet-swatch-pocket-watch-playful-pop-twist-design-2-2-2-2-2-2-2-2-2-2-2-2',
      title: 'Audemars Piguet Swatch Pocket Watch Playful Pop Twist', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/05/audemars-piguet-swatch-pocket-watch-playful-pop-twist-designboom-06.jpg',
      v: 0.38, e: 0.46, polar: 0.48, count: 1331 },
    { id: 'audemars-piguet-swatch-pocket-watch-playful-pop-twist-design-2-2-2-2-2-2-2-2-2-2-2-2-2',
      title: 'Audemars Piguet Swatch Pocket Watch Playful Pop Twist', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/05/audemars-piguet-swatch-pocket-watch-playful-pop-twist-designboom-1.jpg',
      v: 0.46, e: 0.82, polar: 0.32, count: 872 },
    { id: 'laerke-ryom-garments-dezeen-2364-col-8',
      title: 'Laerke Ryom Garments', source: 'Dezeen',
      photo: 'https://static.dezeen.com/uploads/2026/03/laerke-ryom-garments_dezeen_2364_col_8.jpg',
      v: 0.18, e: 0.45, polar: 0.35, count: 1872 },
    { id: 'obro-wearable-collection-leftover-leather-powder-translucent-2',
      title: 'Obro Wearable Collection Leftover Leather Powder Translucent Composite Material Okunote', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/01/obro-wearable-collection-leftover-leather-powder-translucent-composite-material-okunote-designboom-1800-1.jpg',
      v: 0.18, e: 0.47, polar: 0.31, count: 2290 },
    { id: 'multicolor-windows-luca-nichetto-watch-unimatic-designboom-0-2',
      title: 'Multicolor Windows Luca Nichetto Watch UNIMATIC', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/01/multicolor-windows-luca-nichetto-watch-UNIMATIC-designboom-04.jpg',
      v: 0.80, e: 0.13, polar: 0.44, count: 4287 },
    { id: 'kosuke-tsumura-44-pocket-parka-survival-wearable-space-final-2-2-2-2-2',
      title: 'Kosuke Tsumura 44 Pocket Parka Survival Wearable Space Final Home', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/03/kosuke-tsumura-44-pocket-parka-survival-wearable-space-final-home-designboom-07.jpg',
      v: 0.63, e: 0.71, polar: 0.50, count: 3351 },
    { id: 'night-vision-watch-glows-dark-luminescent-resin-green-rubber-2-2-2-2-2',
      title: 'Night Vision Watch Glows Dark Luminescent Resin Green Rubber Bell Ross Br X3', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/02/night-vision-watch-glows-dark-luminescent-resin-green-rubber-bell-ross-br-x3-designboom-03.jpg',
      v: 0.40, e: 0.77, polar: 0.56, count: 3703 },
    { id: 'astronomy-watch-ressence-terumasa-ikeda-dials-planets-design-2-2-2-2',
      title: 'Astronomy Watch Ressence Terumasa Ikeda Dials Planets', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/02/astronomy-watch-ressence-terumasa-ikeda-dials-planets-designboom-07.jpg',
      v: 0.42, e: 0.77, polar: 0.56, count: 2983 },
    { id: 'astronomy-watch-ressence-terumasa-ikeda-dials-planets-design-2-2-2-2-2',
      title: 'Astronomy Watch Ressence Terumasa Ikeda Dials Planets', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/02/astronomy-watch-ressence-terumasa-ikeda-dials-planets-designboom-03.jpg',
      v: 0.85, e: 0.47, polar: 0.38, count: 4361 },
    { id: 'collagen-dinosaur-designer-handbag-lab-grown-leather-designb-2-2-2-2',
      title: 'Collagen Dinosaur Designer Handbag Lab Grown Leather', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/04/collagen-dinosaur-designer-handbag-lab-grown-leather-designboom-1800.jpg',
      v: 0.31, e: 0.70, polar: 0.57, count: 4703 },
    { id: 'multicolor-windows-luca-nichetto-watch-unimatic-designboom-0-2-2',
      title: 'Multicolor Windows Luca Nichetto Watch UNIMATIC', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/01/multicolor-windows-luca-nichetto-watch-UNIMATIC-designboom-06.jpg',
      v: 0.46, e: 0.65, polar: 0.43, count: 3590 },
    { id: 'audemars-piguet-swatch-pocket-watch-playful-pop-twist-design-2-2-2-2-2-2-2-2-2-2-2-2-2-2',
      title: 'Audemars Piguet Swatch Pocket Watch Playful Pop Twist', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/05/audemars-piguet-swatch-pocket-watch-playful-pop-twist-designboom-700-1-400x320-22b08q85r891.jpg',
      v: 0.44, e: 0.61, polar: 0.50, count: 3460 },
    { id: 'jins-eyewear-thomas-heatherwick-glasses-metal-resin-dezeen-2-2-2-2',
      title: 'Jins Eyewear Thomas Heatherwick Glasses Metal Resin', source: 'Dezeen',
      photo: 'https://static.dezeen.com/uploads/2026/05/jins-eyewear-thomas-heatherwick-glasses-metal-resin_dezeen_2364_col_2.jpg',
      v: 0.73, e: 0.39, polar: 0.46, count: 1079 },
    { id: 'astronomy-watch-ressence-terumasa-ikeda-dials-planets-design-2-2-2-2-2-2',
      title: 'Astronomy Watch Ressence Terumasa Ikeda Dials Planets', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/02/astronomy-watch-ressence-terumasa-ikeda-dials-planets-designboom-ban.jpg',
      v: 0.18, e: 0.40, polar: 0.54, count: 4414 },
    { id: 'air-pressure-gauges-mixing-consoles-design-otsuka-lotec-watc-2-2',
      title: 'Air Pressure Gauges Mixing Consoles Design Otsuka Lotec Watch No', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/03/air-pressure-gauges-mixing-consoles-design-otsuka-lotec-watch-no-8-designboom-04.jpg',
      v: 0.73, e: 0.28, polar: 0.35, count: 3065 },
    { id: 'audemars-piguet-swatch-pocket-watch-playful-pop-twist-design-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2',
      title: 'Audemars Piguet Swatch Pocket Watch Playful Pop Twist', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/05/audemars-piguet-swatch-pocket-watch-playful-pop-twist-designboom-02.jpg',
      v: 0.30, e: 0.20, polar: 0.31, count: 420 },
    { id: 'laerke-ryom-garments-dezeen-2364-col-0',
      title: 'Laerke Ryom Garments', source: 'Dezeen',
      photo: 'https://static.dezeen.com/uploads/2026/03/laerke-ryom-garments_dezeen_2364_col_0.jpg',
      v: 0.74, e: 0.63, polar: 0.52, count: 2759 },
    { id: 'air-pressure-gauges-mixing-consoles-design-otsuka-lotec-watc-2-2-2',
      title: 'Air Pressure Gauges Mixing Consoles Design Otsuka Lotec Watch No', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/03/air-pressure-gauges-mixing-consoles-design-otsuka-lotec-watch-no-8-designboom-1800.jpg',
      v: 0.50, e: 0.85, polar: 0.51, count: 968 },
    { id: 'kosuke-tsumura-44-pocket-parka-survival-wearable-space-final-2-2-2-2-2-2',
      title: 'Kosuke Tsumura 44 Pocket Parka Survival Wearable Space Final Home', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/03/kosuke-tsumura-44-pocket-parka-survival-wearable-space-final-home-designboom-02.jpg',
      v: 0.75, e: 0.73, polar: 0.33, count: 2912 },
    { id: 'air-pressure-gauges-mixing-consoles-design-otsuka-lotec-watc-2-2-2-2',
      title: 'Air Pressure Gauges Mixing Consoles Design Otsuka Lotec Watch No', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/03/air-pressure-gauges-mixing-consoles-design-otsuka-lotec-watch-no-8-designboom-03.jpg',
      v: 0.70, e: 0.38, polar: 0.55, count: 2447 },
    { id: 'laerke-ryom-garments-dezeen-2364-col-7',
      title: 'Laerke Ryom Garments', source: 'Dezeen',
      photo: 'https://static.dezeen.com/uploads/2026/03/laerke-ryom-garments_dezeen_2364_col_7.jpg',
      v: 0.35, e: 0.40, polar: 0.34, count: 2508 },
    { id: 'origami-inspired-watch-casio-texture-washi-paper-designboom--2-2-2-2',
      title: 'Origami Inspired Watch Casio Texture Washi Paper', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/02/origami-inspired-watch-casio-texture-washi-paper-designboom-500-1.jpg',
      v: 0.66, e: 0.13, polar: 0.48, count: 2847 },
    { id: 'astronomy-watch-ressence-terumasa-ikeda-dials-planets-design-2-2-2-2-2-2-2',
      title: 'Astronomy Watch Ressence Terumasa Ikeda Dials Planets Ban2', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/02/astronomy-watch-ressence-terumasa-ikeda-dials-planets-designboom-ban2.jpg',
      v: 0.77, e: 0.50, polar: 0.32, count: 4125 },
    { id: 'google-samsung-intelligent-eyewear-design-dezeen-1704-col-4',
      title: 'Google Samsung Intelligent Eyewear Design', source: 'Dezeen',
      photo: 'https://static.dezeen.com/uploads/2026/05/google-samsung-intelligent-eyewear-design_dezeen_1704_col_4.jpg',
      v: 0.76, e: 0.64, polar: 0.57, count: 3914 },
    { id: 'night-vision-watch-glows-dark-luminescent-resin-green-rubber-2-2-2-2-2-2',
      title: 'Night Vision Watch Glows Dark Luminescent Resin Green Rubber Bell Ross Br X3', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/02/night-vision-watch-glows-dark-luminescent-resin-green-rubber-bell-ross-br-x3-designboom-01.jpg',
      v: 0.46, e: 0.66, polar: 0.40, count: 4630 },
    { id: 'multicolor-windows-luca-nichetto-watch-unimatic-designboom-0-2-2-2',
      title: 'Multicolor Windows Luca Nichetto Watch UNIMATIC', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/01/multicolor-windows-luca-nichetto-watch-UNIMATIC-designboom-02.jpg',
      v: 0.32, e: 0.79, polar: 0.35, count: 913 },
    { id: 'night-vision-watch-glows-dark-luminescent-resin-green-rubber-2-2-2-2-2-2-2',
      title: 'Night Vision Watch Glows Dark Luminescent Resin Green Rubber Bell Ross Br X3', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/02/night-vision-watch-glows-dark-luminescent-resin-green-rubber-bell-ross-br-x3-designboom-ban-1.jpg',
      v: 0.29, e: 0.87, polar: 0.58, count: 4131 },
    { id: 'origami-inspired-watch-casio-texture-washi-paper-designboom--2-2-2-2-2',
      title: 'Origami Inspired Watch Casio Texture Washi Paper', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/02/origami-inspired-watch-casio-texture-washi-paper-designboom-05.jpg',
      v: 0.28, e: 0.14, polar: 0.57, count: 1964 },
    { id: 'multicolor-windows-luca-nichetto-watch-unimatic-designboom-0-2-2-2-2',
      title: 'Multicolor Windows Luca Nichetto Watch UNIMATIC', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/01/multicolor-windows-luca-nichetto-watch-UNIMATIC-designboom-03.jpg',
      v: 0.72, e: 0.78, polar: 0.50, count: 5049 },
    { id: 'collagen-dinosaur-designer-handbag-lab-grown-leather-designb-2-2-2-2-2',
      title: 'Collagen Dinosaur Designer Handbag Lab Grown Leather', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/04/collagen-dinosaur-designer-handbag-lab-grown-leather-designboom-02.jpg',
      v: 0.44, e: 0.23, polar: 0.34, count: 4410 },
    { id: 'kosuke-tsumura-44-pocket-parka-survival-wearable-space-final-2-2-2-2-2-2-2',
      title: 'Kosuke Tsumura 44 Pocket Parka Survival Wearable Space Final Home', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/03/kosuke-tsumura-44-pocket-parka-survival-wearable-space-final-home-designboom-1800.jpg',
      v: 0.76, e: 0.15, polar: 0.54, count: 3689 },
    { id: 'kosuke-tsumura-44-pocket-parka-survival-wearable-space-final-2-2-2-2-2-2-2-2',
      title: 'Kosuke Tsumura 44 Pocket Parka Survival Wearable Space Final Home', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/03/kosuke-tsumura-44-pocket-parka-survival-wearable-space-final-home-designboom-01.jpg',
      v: 0.64, e: 0.82, polar: 0.46, count: 1289 },
    { id: 'audemars-piguet-swatch-pocket-watch-playful-pop-twist-design-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2',
      title: 'Audemars Piguet Swatch Pocket Watch Playful Pop Twist', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/05/audemars-piguet-swatch-pocket-watch-playful-pop-twist-designboom-4.jpg',
      v: 0.57, e: 0.85, polar: 0.41, count: 2251 },
    { id: 'air-pressure-gauges-mixing-consoles-design-otsuka-lotec-watc-2-2-2-2-2',
      title: 'Air Pressure Gauges Mixing Consoles Design Otsuka Lotec Watch No', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/03/air-pressure-gauges-mixing-consoles-design-otsuka-lotec-watch-no-8-designboom-06.jpg',
      v: 0.81, e: 0.17, polar: 0.38, count: 3389 },
    { id: 'origami-inspired-watch-casio-texture-washi-paper-designboom--2-2-2-2-2-2',
      title: 'Origami Inspired Watch Casio Texture Washi Paper', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/02/origami-inspired-watch-casio-texture-washi-paper-designboom-03-1.jpg',
      v: 0.42, e: 0.65, polar: 0.34, count: 825 },
    { id: 'origami-inspired-watch-casio-texture-washi-paper-designboom--2-2-2-2-2-2-2',
      title: 'Origami Inspired Watch Casio Texture Washi Paper', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/02/origami-inspired-watch-casio-texture-washi-paper-designboom-ban.jpg',
      v: 0.79, e: 0.52, polar: 0.44, count: 3241 },
    { id: 'astronomy-watch-ressence-terumasa-ikeda-dials-planets-design-2-2-2-2-2-2-2-2',
      title: 'Astronomy Watch Ressence Terumasa Ikeda Dials Planets', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/02/astronomy-watch-ressence-terumasa-ikeda-dials-planets-designboom-02.jpg',
      v: 0.31, e: 0.86, polar: 0.40, count: 3988 },
    { id: 'laerke-ryom-garments-dezeen-2364-col-hero',
      title: 'Laerke Ryom Garments', source: 'Dezeen',
      photo: 'https://static.dezeen.com/uploads/2026/03/laerke-ryom-garments_dezeen_2364_col_hero.jpg',
      v: 0.67, e: 0.62, polar: 0.49, count: 4805 },
    { id: 'astronomy-watch-ressence-terumasa-ikeda-dials-planets-design-2-2-2-2-2-2-2-2-2',
      title: 'Astronomy Watch Ressence Terumasa Ikeda Dials Planets', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/02/astronomy-watch-ressence-terumasa-ikeda-dials-planets-designboom-01.jpg',
      v: 0.46, e: 0.70, polar: 0.53, count: 4438 },
    { id: 'multicolor-windows-luca-nichetto-watch-unimatic-designboom-0-2-2-2-2-2',
      title: 'Multicolor Windows Luca Nichetto Watch UNIMATIC', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/01/multicolor-windows-luca-nichetto-watch-UNIMATIC-designboom-01.jpg',
      v: 0.83, e: 0.35, polar: 0.42, count: 4088 },
    { id: 'air-pressure-gauges-mixing-consoles-design-otsuka-lotec-watc-2-2-2-2-2-2',
      title: 'Air Pressure Gauges Mixing Consoles Design Otsuka Lotec Watch No', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/03/air-pressure-gauges-mixing-consoles-design-otsuka-lotec-watch-no-8-designboom-02.jpg',
      v: 0.75, e: 0.60, polar: 0.46, count: 5016 },
    { id: 'astronomy-watch-ressence-terumasa-ikeda-dials-planets-design-2-2-2-2-2-2-2-2-2-2',
      title: 'Astronomy Watch Ressence Terumasa Ikeda Dials Planets', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/02/astronomy-watch-ressence-terumasa-ikeda-dials-planets-designboom-05.jpg',
      v: 0.70, e: 0.62, polar: 0.53, count: 1946 },
    { id: 'brushed-metal-fold-watch-time-shadow-layered-architectural-d-2',
      title: 'Brushed Metal Fold Watch Time Shadow Layered Architectural Dials01', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/02/brushed-metal-fold-watch-time-shadow-layered-architectural-dials01.jpg',
      v: 0.78, e: 0.49, polar: 0.53, count: 4726 },
    { id: 'laerke-ryom-garments-dezeen-2364-col-4',
      title: 'Laerke Ryom Garments', source: 'Dezeen',
      photo: 'https://static.dezeen.com/uploads/2026/03/laerke-ryom-garments_dezeen_2364_col_4.jpg',
      v: 0.60, e: 0.74, polar: 0.42, count: 1791 },
    { id: 'obro-wearable-collection-leftover-leather-powder-translucent-2-2',
      title: 'Obro Wearable Collection Leftover Leather Powder Translucent Composite Material Okunote', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/01/obro-wearable-collection-leftover-leather-powder-translucent-composite-material-okunote-designboom-1800-2.jpg',
      v: 0.21, e: 0.37, polar: 0.46, count: 4920 },
    { id: 'night-vision-watch-glows-dark-luminescent-resin-green-rubber-2-2-2-2-2-2-2-2',
      title: 'Night Vision Watch Glows Dark Luminescent Resin Green Rubber Bell Ross Br X3', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/02/night-vision-watch-glows-dark-luminescent-resin-green-rubber-bell-ross-br-x3-designboom-05.jpg',
      v: 0.71, e: 0.33, polar: 0.55, count: 1598 },
    { id: 'parinamah-architects-sabri-gold-and-diamonds-jewellery-store',
      title: 'Parinamah Architects Sabri Gold and Diamonds Jewellery Store Tiruppur India Sq3', source: 'Dezeen',
      photo: 'https://static.dezeen.com/uploads/2026/03/parinamah-architects-sabri-gold-and-diamonds-jewellery-store-tiruppur-india-sq3.jpg',
      v: 0.82, e: 0.42, polar: 0.42, count: 1917 },
    { id: 'heatherwick-studio-eyewear-jins-sq',
      title: 'Heatherwick Studio Eyewear Jins', source: 'Dezeen',
      photo: 'https://static.dezeen.com/uploads/2026/05/heatherwick-studio-eyewear-jins-sq.jpg',
      v: 0.74, e: 0.60, polar: 0.41, count: 4866 },
    { id: 'origami-inspired-watch-casio-texture-washi-paper-designboom--2-2-2-2-2-2-2-2',
      title: 'Origami Inspired Watch Casio Texture Washi Paper', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/02/origami-inspired-watch-casio-texture-washi-paper-designboom-06.jpg',
      v: 0.25, e: 0.64, polar: 0.49, count: 873 },
    { id: 'laerke-ryom-garments-dezeen-2364-col-11',
      title: 'Laerke Ryom Garments', source: 'Dezeen',
      photo: 'https://static.dezeen.com/uploads/2026/03/laerke-ryom-garments_dezeen_2364_col_11.jpg',
      v: 0.18, e: 0.76, polar: 0.49, count: 463 },
    { id: 'audemars-piguet-swatch-pocket-watch-playful-pop-twist-design-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2',
      title: 'Audemars Piguet Swatch Pocket Watch Playful Pop Twist Large', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/05/audemars-piguet-swatch-pocket-watch-playful-pop-twist-designboom-large.jpg',
      v: 0.56, e: 0.31, polar: 0.33, count: 1817 },
    { id: 'kosuke-tsumura-44-pocket-parka-survival-wearable-space-final-2-2-2-2-2-2-2-2-2',
      title: 'Kosuke Tsumura 44 Pocket Parka Survival Wearable Space Final Home', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/03/kosuke-tsumura-44-pocket-parka-survival-wearable-space-final-home-designboom-10.jpg',
      v: 0.65, e: 0.29, polar: 0.45, count: 3210 },
    { id: 'night-vision-watch-glows-dark-luminescent-resin-green-rubber-2-2-2-2-2-2-2-2-2',
      title: 'Night Vision Watch Glows Dark Luminescent Resin Green Rubber Bell Ross Br X3', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/02/night-vision-watch-glows-dark-luminescent-resin-green-rubber-bell-ross-br-x3-designboom-04.jpg',
      v: 0.79, e: 0.86, polar: 0.55, count: 4873 },
    { id: 'google-samsung-intelligent-eyewear-design-dezeen-1704-col-2',
      title: 'Google Samsung Intelligent Eyewear Design', source: 'Dezeen',
      photo: 'https://static.dezeen.com/uploads/2026/05/google-samsung-intelligent-eyewear-design_dezeen_1704_col_2.jpg',
      v: 0.39, e: 0.49, polar: 0.50, count: 1455 },
    { id: 'multicolor-windows-luca-nichetto-watch-unimatic-designboom-1',
      title: 'Multicolor Windows Luca Nichetto Watch UNIMATIC', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/01/multicolor-windows-luca-nichetto-watch-UNIMATIC-designboom-1800.jpg',
      v: 0.23, e: 0.64, polar: 0.48, count: 1897 },
    { id: 'hhero-eatherwick-studio-jins-eyewear-debut-collection-1',
      title: 'Hhero Eatherwick Studio Jins Eyewear Debut Collection', source: 'Dezeen',
      photo: 'https://static.dezeen.com/uploads/2026/05/hhero-eatherwick-studio-jins-eyewear-debut-collection-1.jpg',
      v: 0.32, e: 0.64, polar: 0.49, count: 1969 },
    { id: 'audemars-piguet-swatch-pocket-watch-playful-pop-twist-design-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2',
      title: 'Audemars Piguet Swatch Pocket Watch Playful Pop Twist', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/05/audemars-piguet-swatch-pocket-watch-playful-pop-twist-designboom-11.jpg',
      v: 0.81, e: 0.85, polar: 0.46, count: 2713 },
    { id: 'brushed-metal-fold-watch-time-shadow-layered-architectural-d-2-2',
      title: 'Brushed Metal Fold Watch Time Shadow Layered Architectural', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/02/brushed-metal-fold-watch-time-shadow-layered-architectural-dials1800.jpg',
      v: 0.69, e: 0.23, polar: 0.54, count: 3128 },
    { id: 'kosuke-tsumura-44-pocket-parka-survival-wearable-space-final-2-2-2-2-2-2-2-2-2-2',
      title: 'Kosuke Tsumura 44 Pocket Parka Survival Wearable Space Final Home', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/03/kosuke-tsumura-44-pocket-parka-survival-wearable-space-final-home-designboom-04.jpg',
      v: 0.41, e: 0.55, polar: 0.41, count: 4906 },
    { id: 'night-vision-watch-glows-dark-luminescent-resin-green-rubber-2-2-2-2-2-2-2-2-2-2',
      title: 'Night Vision Watch Glows Dark Luminescent Resin Green Rubber Bell Ross Br X3 Ban2', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/02/night-vision-watch-glows-dark-luminescent-resin-green-rubber-bell-ross-br-x3-designboom-ban2.jpg',
      v: 0.64, e: 0.56, polar: 0.53, count: 2536 },
    { id: 'collagen-dinosaur-designer-handbag-lab-grown-leather-designb-2-2-2-2-2-2',
      title: 'Collagen Dinosaur Designer Handbag Lab Grown Leather', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/04/collagen-dinosaur-designer-handbag-lab-grown-leather-designboom-04.jpg',
      v: 0.26, e: 0.84, polar: 0.35, count: 2229 },
    { id: 'air-pressure-gauges-mixing-consoles-design-otsuka-lotec-watc-2-2-2-2-2-2-2',
      title: 'Air Pressure Gauges Mixing Consoles Design Otsuka Lotec Watch No', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/03/air-pressure-gauges-mixing-consoles-design-otsuka-lotec-watch-no-8-designboom-01.jpg',
      v: 0.33, e: 0.77, polar: 0.46, count: 4065 },
    { id: 'hhero-eatherwick-studio-jins-eyewear-debut-collection',
      title: 'Hhero Eatherwick Studio Jins Eyewear Debut Collection', source: 'Dezeen',
      photo: 'https://static.dezeen.com/uploads/2026/05/hhero-eatherwick-studio-jins-eyewear-debut-collection.jpg',
      v: 0.54, e: 0.45, polar: 0.40, count: 5126 },
    { id: 'kosuke-tsumura-44-pocket-parka-survival-wearable-space-final-2-2-2-2-2-2-2-2-2-2-2',
      title: 'Kosuke Tsumura 44 Pocket Parka Survival Wearable Space Final Home', source: 'Designboom',
      photo: 'https://static.designboom.com/wp-content/uploads/2026/03/kosuke-tsumura-44-pocket-parka-survival-wearable-space-final-home-designboom-09.jpg',
      v: 0.79, e: 0.44, polar: 0.57, count: 1491 },
  ]
};
